version: '3'

services:
  flexptlbgeweb:
    image: flexptlbgeweb
    container_name: flexptlbgeweb
    build:
      context: .
      dockerfile: Dockerfile
      args:
        source: bin/Debug/netcoreapp2.0/publish
    expose:
      - 5000