version: '3'

services:
  flexptlbgeservice:
    image: flexptlbgeservice
    container_name: flexptlbgeservice
    build:
      context: .
      dockerfile: Dockerfile
      args:
        source: bin/Debug/netcoreapp2.0/publish
    expose:
       - 5000